name: app
description: Blind meal project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_modular: ^1.3.2
  mobx: ^1.0.0
  flutter_mobx: ^1.0.0
  freezed: ^0.11.5
  json_serializable: ^3.4.0
  firebase_core: ^0.4.0+8
  firebase_auth: ^0.15.0+1
  cloud_firestore: ^0.13.6
  firebase_analytics: ^5.0.16
  introduction_screen: ^1.0.7
  flutter_svg: ^0.18.0
  intl: ^0.16.1
  firebase_crashlytics: ^0.1.4+1
  bot_toast: ^3.0.3
  email_validator: ^1.0.0
  flutter_sim_country_code: ^0.0.3
  country_provider: ^0.0.1
  country_icons: ^1.1.1
  percent_indicator: ^2.1.5
  device_preview: ^0.4.8




dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  mobx_codegen: ^1.0.0
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  image_path: "assets/icons/icon1.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/onboarding/
    - assets/logo/
    - assets/icons/
    - assets/icons/social_media/
    - assets/images/
    - assets/images/diets/
    - assets/images/recommendedFood/
